### ISSUE TITLE
Help anyone? (2)

### ISSUE THREAD

**Issue by EggPool** [EggPool/BismuthRPC#5]
https://github.com/EggPool/BismuthRPC/blob/257d20cd43574b8148d13db89c63ac73fa7c46e1/RPCServer/rpcwallet.py#L194

If you want to help, I'm trying to define small isolated tasks.

**Comment by EggPool** [comment]
Here is what the file should contain  
txt file, one address per line.  
a single account can hold many addresses  
separator is a single space  
privkey as in the json wallet (be it encrypted or not), RESERVED (timestamp in future version), then pairs of properties, for now just account and address
```
# Wallet dump created by bismuthd v0.1.2
# * Created on 2014-04-29T20:46:09Z
# Wallet is Uncrypted

privkey1 RESERVED account=account1 addr=address1
privkey2 RESERVED account=account1 addr=address2
privkey3 RESERVED account=account2 addr=address3
```

**Comment by rvanduiven** [comment]
PR created

**Comment by EggPool** [comment]
Looked good, merged.
Thanks!
